#!/usr/bin/env python

import subprocess

add_list = ["66.112.221.61","c19s1.jamjams.net","c19s2.jamjams.net","c19s3.jamjams.net","c19s4.jamjams.net","c19s5.jamjams.net"]
processes = []

for address in add_list:
	processes.append(subprocess.Popen(["ping",address], stdout=subprocess.PIPE, bufsize = 1))

pCount = 0
for p in processes:
	for line in iter(p.stdout.readline, b''):
		if line.find("Reply from") != -1:
			print add_list[pCount], "is [OK]"
			p.terminate()
			break
		elif line.find("Request timed out.") != -1:
			print add_list[pCount], "is [FAIL]"
			p.terminate()
			break
	pCount += 1